name: tfsec                               # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  tfsec:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
